/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BDM: typeof import('./src/components/BDM.vue')['default']
    ChatUi: typeof import('./src/components/ChatUi.vue')['default']
    Demo: typeof import('./src/components/Demo.vue')['default']
    Demo2: typeof import('./src/components/Demo2.vue')['default']
    DictAddDialog: typeof import('./src/components/Dictionary/DictAddDialog.vue')['default']
    DictCategoryChips: typeof import('./src/components/Dictionary/Sidebar/DictCategoryChips.vue')['default']
    Dictionary: typeof import('./src/components/Dictionary.vue')['default']
    DictionaryDialog: typeof import('./src/components/Translate/DictionaryDialog.vue')['default']
    DictSearchbar: typeof import('./src/components/Dictionary/Sidebar/DictSearchbar.vue')['default']
    DictSidebar: typeof import('./src/components/Dictionary/DictSidebar.vue')['default']
    DictWordDetail: typeof import('./src/components/Dictionary/DictWordDetail.vue')['default']
    DictWordList: typeof import('./src/components/Dictionary/Sidebar/DictWordList.vue')['default']
    FeedbackDialog: typeof import('./src/components/Translate/FeedbackDialog.vue')['default']
    Generate: typeof import('./src/components/Generate.vue')['default']
    Llava: typeof import('./src/components/Llava.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    ManualForm: typeof import('./src/components/Dictionary/Dialog/ManualForm.vue')['default']
    Meal: typeof import('./src/components/Meal.vue')['default']
    RAG: typeof import('./src/components/RAG.vue')['default']
    Sample: typeof import('./src/components/sample.vue')['default']
    SnackBar: typeof import('./src/components/Translate/SnackBar.vue')['default']
    TranslateInput: typeof import('./src/components/Translate/TranslateInput.vue')['default']
    TranslateOutput: typeof import('./src/components/Translate/TranslateOutput.vue')['default']
    TranslateV2: typeof import('./src/components/translateV2.vue')['default']
    TranslateVDB: typeof import('./src/components/translateVDB.vue')['default']
    UploadFile: typeof import('./src/components/Dictionary/Dialog/UploadFile.vue')['default']
    Vision: typeof import('./src/components/Vision.vue')['default']
  }
}
