/**
* main.js
*
* Bootstraps Vuetify and other plugins then mounts the App`
*/

// Plugins
import { createI18n } from 'vue-i18n'
import { registerPlugins } from '@/plugins'
// Components
import App from './App.vue'
import * as directives from 'vuetify/directives'
// Composables
import { createApp } from 'vue'
import { createVuetify } from 'vuetify';


const app = createApp(App)
const vuetify = createVuetify({
    directives,
});
app.use(vuetify);
const i18n = createI18n({
    locale: 'vi',
    fallbackLocale: 'en',
    legacy: false,
    messages: {
        en: {
            nav: {
                language: 'English',
                translate: 'Translate',
                translateVDB: 'Translate VDB (Testing)',
                dictionary: 'Dictionary',
                appTitle: 'VG Local LLM',
                llava: 'Vision',
                visionMode: 'Vision Mode',
                dictionary: 'Dictionary',
                logout: 'Logout',
                dept: 'Department',
            },
            trans: {
                warning: 'Warning: translation content may not be accurate. We are in the testing phase. AI may return harmful content.',
                visionMode: 'Vision Mode: Upload images and use OCR to extract text for translation',
                uploadImage: 'Upload Image',
                clearImage: 'Clear Image',
                imageReady: 'Image Ready',
                internalDict: 'Internal Dictionary',
                translate: 'Translate',
                copy: 'Copy',
                sourceTransPlaceholder: 'Input your text here...',
                transPlaceholder: 'Translation results display here...',
                enhanceTheTranslation: 'Enhance the translation',
                enhancedVersion: 'Enhanced Version',
                waitingForUserInput: 'Waiting for user input...',
                useTheEnhancedVersion: 'Use the enhanced',
                transFeedbackTitle: 'Translation Feedback',
                sourceLangDetected: 'Language detected: ',
                enhanceSourceText: 'Enhance the source text',
                enhancedSourceOutput: 'Output',
                fixingGrammar: 'Fixing grammar',
                dictLookup: 'Dictionary Lookup',
                exampleTitle: 'Example',
                synonymsTitle: 'Synonyms',
                antonymsTitle: 'Antonyms',
                idiomsTitle: 'Idioms',
                otherMeaningTitle: 'Other Meanings',
                dictAiWarning: 'Warning: AI may return harmful content.',
                fastSpeed: 'Fast Speed',
                normal: 'Normal',
                highQuality: 'High Quality',
                highestQuality: 'Highest Quality',
                fastSpeedDesc: 'Quick response, good quality for most texts',
                normalDesc: 'Balanced speed and quality, supports vision',
                highQualityDesc: 'Slower but higher accuracy, better for complex texts',
                highestQualityDesc: 'Slowest but best quality, premium reasoning model',
                enterAtLeastOneLangAndCategory: "Please enter at least one target language and one category.",
            },
            dict: {
                en: 'English',
                vi: 'Vietnamese',
                cn: 'Chinese Simplified',
                'zh-tw': 'Chinese Traditional',
                newWord: 'New Word',
                searchPlaceholder: 'Search...',
                autoTranslate: 'Auto Translate',
                saveNewWord: 'Save New Word',
                updateWord: 'Update Word',
                cancel: 'Cancel',
                cats: 'Categories',
                catsAll: 'All',
                descEn: 'Description (English)',
                descVi: 'Description (Vietnamese)',
                descCn: 'Description (CN- Simplified)',
                descTw: 'Description (CN - Traditional)',
                deleteWord: 'Delete Word',
                deleteWordConfirm: 'Are you sure you want to delete this word?',
                dictWordDeleted: 'Word deleted.',
                dictWordNotDeleted: 'Word not deleted. Error occurred.',
                reset: 'Reset',
                selectWordToView: "Please select a word to view details.",
                selectAtLeastOneCategory: "Please select at least one category.",
                addManually: 'Add Manually',
                uploadFile: 'Upload File',
                selectFile: 'Select File',
                fileFormatInfo: 'Supported formats: JSON, CSV, Excel (.xlsx)',
                preview: 'Preview',
                uploadWords: 'Upload {count} words',
                unsupportedFileFormat: 'Unsupported file format',
                fileParseError: 'Error parsing file',
                bulkUploadSuccess: 'Words uploaded successfully',
                bulkUploadError: 'Error uploading words',
                description: 'Description',
            },
            ui: {
                cancel: 'Cancel',
                submit: 'Submit',
                apply: 'Apply',
            },
            notify: {
                copied: 'Translation content copied.',
                emptyInput: 'Please enter the content to translate.',
                dictNewWordSaved: 'New word saved.',
                dictNewWordNotSaved: 'New word not saved. Error occurred.',
                cannotTranslate: 'Cannot translate.',
                saveNewWordConfirm: 'Are you sure you want to save / update this new word?',
                errorAndWaitForRevise: 'Error occurred. Please wait for the revise.',
                thankYouForRating: 'Thank you for rating!',
                yourFeedbackIsVeryImportant: 'Your feedback is very important to us.',
                thankYouForRating: 'Thank you for rating!',
                checkSourceFormat: 'Please check the source format.',
            },
            login: {
                title: 'Sign In',
                subtitle: 'Access the dictionary',
                username: 'Username',
                password: 'Password',
                signIn: 'Sign In',
                required: 'This field is required',
                invalidCredentials: 'Invalid username or password',
                networkError: 'Network error. Please try again.',
                accessDenied: 'Access denied. You do not have permission to use the dictionary.'
            }
        },
        vi: {
            nav: {
                language: 'Tiếng Việt',
                translate: 'Dịch tự động',
                translateVDB: 'Dịch VDB (Thử nghiệm)',
                dictionary: 'Từ điển',
                appTitle: 'VG LLM',
                llava: 'Vision',
                visionMode: 'Chế độ Vision',
                dictionary: 'Từ điển',
                logout: 'Đăng xuất',
                dept: 'Phòng ban',
            },
            trans: {
                warning: 'Thận trọng: nội dung dịch có thể không chính xác. Chúng tôi đang trong giai đoạn thử nghiệm. AI có thể trả lại nội dung có hại.',
                visionMode: 'Chế độ Vision: Tải lên hình ảnh và sử dụng OCR để trích xuất văn bản cần dịch',
                uploadImage: 'Tải ảnh lên',
                clearImage: 'Xóa ảnh',
                imageReady: 'Đã sẵn sàng ảnh',
                internalDict: 'Từ điển nội bộ',
                translate: 'Dịch',
                copy: 'Sao chép',
                sourceTransPlaceholder: 'Nhập văn bản của bạn ở đây...',
                transPlaceholder: 'Kết quả dịch hiển thị ở đây...',
                enhanceTheTranslation: 'Dịch Nâng cao',
                enhancedVersion: 'Phiên bản cải thiện',
                enhanceTheTranslation: 'Tối ưu bản dịch',
                waitingForUserInput: 'Đang chờ văn bản để dịch...',
                useTheEnhancedVersion: 'Áp dụng',
                transFeedbackTitle: 'Góp ý về  bản dịch',
                sourceLangDetected: 'Ngôn ngữ nguồn: ',
                enhanceSourceText: 'Tối ưu văn bản nguồn',
                enhancedSourceOutput: 'Kết quả',
                fixingGrammar: 'Sửa lỗi ngữ pháp',
                dictLookup: 'Tra từ điển',
                exampleTitle: 'Ví dụ',
                synonymsTitle: 'Từ đồng nghĩa',
                antonymsTitle: 'Từ trái nghĩa',
                idiomsTitle: 'Thành ngữ',
                otherMeaningTitle: 'Nghĩa khác',
                dictAiWarning: 'Cảnh báo: AI có thể trả lại nội dung có hại.',
                fastSpeed: 'Tốc Độ Nhanh',
                normal: 'Bình Thường',
                highQuality: 'Chất Lượng Cao',
                highestQuality: 'Chất Lượng Tối Đa',
                fastSpeedDesc: 'Phản hồi nhanh, chất lượng tốt cho hầu hết văn bản',
                normalDesc: 'Cân bằng tốc độ và chất lượng, hỗ trợ hình ảnh',
                highQualityDesc: 'Chậm hơn nhưng độ chính xác cao, tốt cho văn bản phức tạp',
                highestQualityDesc: 'Chậm nhất nhưng chất lượng tốt nhất, mô hình suy luận cao cấp',
            },
            dict: {
                en: 'Anh ngữ',
                vi: 'Tiếng Việt',
                zh: 'Trung Quốc',
                cn: 'Trung Quốc giản thể',
                'zh-tw': 'Trung Quốc phồn thể',
                newWord: 'Từ mới',
                searchPlaceholder: 'Tìm kiếm...',
                updateWord: 'Cập nhật từ',
                autoTranslate: 'Dịch tự động',
                saveNewWord: 'Lưu từ mới',
                updateWord: 'Cập nhật từ',
                cancel: 'Hủy',
                cats: 'Danh mục',
                catsAll: 'Tất cả',
                descEn: 'Mô tả (Tiếng Anh)',
                descZh: 'Mô tả (Trung Quốc)',
                descCn: 'Mô tả (Trung Quốc giản thể)',
                descTw: 'Mô tả (Trung Quốc phồn thể)',
                descVi: 'Mô tả (Tiếng Việt)',
                deleteWord: 'Xóa từ',
                deleteWordConfirm: 'Bạn có chắc chắn muốn xóa từ này không?',
                dictWordDeleted: 'Từ đã bị xóa.',
                dictWordNotDeleted: 'Từ không bị xóa. Đã xảy ra lỗi.',
                reset: 'Đặt lại',
                selectWordToView: "Vui lòng chọn một từ để xem chi tiết.",
                enterAtLeastOneLangAndCategory: "Vui lòng nhập ít nhất một ngôn ngữ và một danh mục.",
                selectAtLeastOneCategory: "Vui lòng chọn ít nhất một danh mục.",
                addManually: 'Thêm thủ công',
                uploadFile: 'Tải tệp lên',
                selectFile: 'Chọn tệp',
                fileFormatInfo: 'Định dạng được hỗ trợ: JSON, CSV, Excel (.xlsx)',
                preview: 'Xem trước',
                uploadWords: 'Tải lên {count} từ',
                unsupportedFileFormat: 'Định dạng tệp không được hỗ trợ',
                fileParseError: 'Lỗi khi phân tích tệp',
                bulkUploadSuccess: 'Từ đã được tải lên thành công',
                bulkUploadError: 'Lỗi khi tải từ lên',
                enterAtLeastOneLangAndCategory: "Vui lòng nhập ít nhất một ngôn ngữ và một danh mục.",
            },
            ui: {
                cancel: 'Hủy',
                submit: 'Gửi Đi',
                apply: 'Áp dụng',
            },
            notify: {
                copied: 'Đã sao chép nội dung dịch.',
                emptyInput: 'Vui lòng nhập nội dung cần dịch.',
                dictNewWordSaved: 'Từ mới đã được lưu.',
                dictNewWordNotSaved: 'Từ mới không được lưu. Đã xảy ra lỗi.',
                cannotTranslate: 'Không thể dịch.',
                saveNewWordConfirm: 'Bạn có chắc chắn muốn lưu / cập nhật từ mới này không?',
                errorAndWaitForRevise: 'Đã xảy ra lỗi. Vui lòng chờ máy tự sửa lỗi. ',
                thankYouForRating: 'Cảm ơn bạn đã đánh giá!',
                yourFeedbackIsVeryImportant: 'Ý kiến của bạn rất quan trọng với chúng tôi.',
                checkSourceFormat: 'Vui lòng kiểm tra định dạng nguồn dịch.',
            },
            login: {
                title: 'Đăng nhập',
                subtitle: 'Truy cập từ điển',
                username: 'Tên đăng nhập',
                password: 'Mật khẩu',
                signIn: 'Đăng nhập',
                required: 'Vui lòng nhập đầy đủ',
                invalidCredentials: 'Sai tên đăng nhập hoặc mật khẩu',
                networkError: 'Lỗi mạng. Vui lòng thử lại.',
                accessDenied: 'Từ chối truy cập. Bạn không có quyền sử dụng từ điển.'
            },
        }, 
        zh: {
            nav: {
                language: '中文',
                translate: '自动翻译',
                translateVDB: '翻译VDB (测试)',
                dictionary: '字典',
                appTitle: 'VG LLM',
                llava: 'Llava',
                visionMode: '视觉模式',
                dictionary: '字典',
                logout: '登出',
                dept: '部门',
            },
            trans: {
                warning: '警告：翻译内容可能不准确。我们正在测试阶段。AI可能会返回有害内容。',
                visionMode: '视觉模式：上传图片并使用OCR提取文字进行翻译',
                uploadImage: '上传图片',
                clearImage: '清除图片',
                imageReady: '图片已就绪',
                internalDict: '内部字典',
                translate: '翻译',
                copy: '复制',
                sourceTransPlaceholder: '在此输入您的文本...',
                transPlaceholder: '翻译结果在此显示...',
                enhanceTheTranslation: '高级翻译',
                enhancedVersion: '增强版本',
                enhanceTheTranslation: '优化翻译',
                waitingForUserInput: '等待用户输入...',
                useTheEnhancedVersion: '使用增强版',
                transFeedbackTitle: '翻译反馈',
                sourceLangDetected: '检测到语言： ',
                enhanceSourceText: '优化源文本',
                enhancedSourceOutput: '输出',
                fixingGrammar: '修正语法',
                dictLookup: '字典查询',
                exampleTitle: '例子',
                synonymsTitle: '同义词',
                antonymsTitle: '反义词',
                idiomsTitle: '成语',
                otherMeaningTitle: '其他含义',
                dictAiWarning: '警告：AI可能会返回有害内容。',
                fastSpeed: '快速模式',
                normal: '标准模式',
                highQuality: '高质量模式',
                highestQuality: '最高质量模式',
                fastSpeedDesc: '快速响应，适合大多数文本的良好质量',
                normalDesc: '平衡速度和质量，支持图像识别',
                highQualityDesc: '较慢但精度更高，适合复杂文本',
                highestQualityDesc: '最慢但质量最佳，顶级推理模型',
            },
            dict: {
                en: '英语',
                vi: '越南语',
                zh: '中文',
                cn: '简体中文',
                'zh-tw': '繁体中文',
                newWord: '新词',
                searchPlaceholder: '搜索...',
                updateWord: '更新词汇',
                autoTranslate: '自动翻译',
                saveNewWord: '保存新词',
                updateWord: '更新词汇',
                cancel: '取消',
                cats: '类别',
                catsAll: '所有',
                descEn: '描述（英语）',
                descVi: '描述（越南语）',
                descCn: '描述（简体中文）',
                descTw: '描述（繁体中文）',
                deleteWord: '删除词汇',
                deleteWordConfirm: '您确定要删除此词汇吗？',
                dictWordDeleted: '词汇已删除。',
                dictWordNotDeleted: '词汇未删除。发生错误。',
                reset: '重置',
                selectWordToView: "请选择一个词汇以查看详情。",
                enterAtLeastOneLangAndCategory: "请输入至少一种目标语言和一个类别。",
                selectAtLeastOneCategory: "请选择至少一个类别。",
                addManually: '手动添加',
                uploadFile: '上传文件',
                selectFile: '选择文件',
                fileFormatInfo: '支持的格式：JSON，CSV，Excel（.xlsx）',
                preview: '预览',
                uploadWords: '上传 {count} 个词',
                unsupportedFileFormat: '不支持的文件格式',
                fileParseError: '解析文件时出错',
                bulkUploadSuccess: '词汇上传成功',
                bulkUploadError: '上传词汇时出错',
                enterAtLeastOneLangAndCategory: "请输入至少一种目标语言和一个类别。",
            },
            ui: {
                cancel: '取消',
                submit: '提交',
                apply: '应用',
            },
            notify: {
                copied: '已复制翻译内容。',
                emptyInput: '请输入要翻译的内容。',
                dictNewWordSaved: '新词已保存。',
                dictNewWordNotSaved: '新词未保存。发生错误。',
                cannotTranslate: '无法翻译。',
                saveNewWordConfirm: '您确定要保存/更新此新词吗？',
                errorAndWaitForRevise: '发生错误。请等待修订。',
                thankYouForRating: '感谢您的评分！',
                yourFeedbackIsVeryImportant: '您的反馈对我们非常重要。',
                checkSourceFormat: '请检查源格式。',
            },
              login: {
                title: '登录',
                subtitle: '访问字典和翻译工具',
                username: '用户名',
                password: '密码',
                signIn: '登录',
                required: '此字段为必填项',
                invalidCredentials: '用户名或密码错误',
                networkError: '网络错误，请重试。',
                accessDenied: '拒绝访问。您没有使用字典的权限。'
            },
        }
    }});
    app.use(i18n)
    registerPlugins(app)
    app.mount('#app')
